# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Office of Innovation & Entrepreneurship
email: mofie@cityofsacramento.org
description: > # this means to ignore newlines until "baseurl:"
  An open data effort to improve economic mobility for all Americans.
baseurl: "" # the subpath of your site, e.g. /blog
email: opportunity-data@listserv.gsa.gov
url: http://opportunity.census.gov # the base hostname & protocol for your site
repo_url: https://github.com/uscensusbureau/opportunity

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - index_includes
